spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wyb12/springcloud.git
          search-paths:
          - configfiles
      label: dev
server:
  port: 8888
